version: '3.7'

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    ports:
      - ${HTTP_PORT:-8080}:80
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - adonis
    restart: always
 
  adonis:
    build:
      context: ./
      dockerfile: docker/adonis.docker
    working_dir: /var/www/adonis
    volumes:
      - ./main:/var/www/adonis
    depends_on:
      - postgres
      - redis
    environment:
      - DEBUG=$DEBUG
    restart: always
  admin-panel:
    build:
      context: ./
      dockerfile: docker/admin-panel.docker
    working_dir: /var/www/admin-panel
    volumes:
      - ./admin-panel:/var/www/admin-panel
    depends_on:
      - postgres
      - redis
    environment:
      - DEBUG=$DEBUG
    restart: always

  postgres:
    image: postgis/postgis:12-3.0-alpine
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
    restart: always
    ports:
        - 54329:5432
  redis:  
    image: redis
    ports:
      - "6379"
    restart: always


